### ISSUE TITLE
Header : Sign up

### ISSUE THREAD

**Issue by Krina-Addweb** [narendra-addweb/MyImmoPix#10]
1) Registration process,fields,& mail should be same for whole site wherever they used registration .i.e. Sign up from Header Button & From My account page is different as precess, fields & mails .
2) When a user registers with header sign up popup, the WordPress default, mail is received & when we register through My account page , the custom mail is 
Received.
3) Fields are different from registering a new account, while registering from my-account (http://www.myimmopix.com/my-account/) and clicking on ""Sign Up"" button at the topbar.

https://www.evernote.com/l/Ag7oYsJ95PlGpKkTeEiHEZWNZvkKQwNejwc
https://www.evernote.com/l/Ag6540CN_31BfaNfo4Lo8BF_Fup__C71JhU

**Comment by narendra-addweb** [comment]
Please check.

We use same page for registration process(My account page) so both are work same now.
