### ISSUE TITLE
Language specific : Translation is missing from the my account page

### ISSUE THREAD

**Issue by Krina-Addweb** [narendra-addweb/MyImmoPix#101]
![image](https://cloud.githubusercontent.com/assets/14847553/13312612/21aaea4a-dbbe-11e5-9113-a4ab73f71f5a.png)

**Comment by Maxfavier** [comment]
Still some missing translations.
Please review.

<img width="1223" alt="capture d ecran 2016-03-21 11 54 25" src="https://cloud.githubusercontent.com/assets/17143257/13916586/c6b69524-ef5b-11e5-879d-cf9a477a465d.png">

**Comment by narendra-addweb** [comment]
For consistency, use common side bar cart like already used in [credit page](http://myimmopix.addwebprojects.com/credit/)

**Comment by Maxfavier** [comment]
In FR: "for" translated into "pour"

<img width="189" alt="capture d ecran 2016-03-22 15 18 34" src="https://cloud.githubusercontent.com/assets/17143257/13954506/648e0378-f041-11e5-81dd-ff3f88e78219.png">
