### ISSUE TITLE
Project detail: Upload photo time duration

### ISSUE THREAD

**Issue by narendra-addweb** [narendra-addweb/MyImmoPix#103]
What is the correct here? 
- Display photo upload time duration bases on first uploaded photo

_OR_
- Display photo upload time duration based on recently uploaded photo

**NOTE:** Current functionality is display upload time duration based on "First uploaded photo". Please let me know your thoughts on it.

![project_detail_uploadtime](https://cloud.githubusercontent.com/assets/15060303/13343910/364b92a6-dc77-11e5-8e42-e5b24e7e74ca.png)

**Comment by Maxfavier** [comment]
Thanks for the query. We can keep it on the first upload base.
