### ISSUE TITLE
Language specific Designing : Review project page

### ISSUE THREAD

**Issue by Krina-Addweb** [narendra-addweb/MyImmoPix#105]
Need to Design Order Summary button & uploaded time details when we have long text.
![image](https://cloud.githubusercontent.com/assets/14847553/13345415/a9a494de-dc84-11e5-9641-d95044fa8e57.png)

**Comment by Maxfavier** [comment]
"Second(s)" should be "Seconde(s)" in French.

<img width="308" alt="capture d ecran 2016-03-14 17 11 57" src="https://cloud.githubusercontent.com/assets/17143257/13750917/e74b4f54-ea07-11e5-9f69-44cfef404482.png">
