### ISSUE TITLE
Review project : Error

### ISSUE THREAD

**Issue by Krina-Addweb** [narendra-addweb/MyImmoPix#107]
Review projects 
![screen shot 2016-02-29 at 1 51 59 pm](https://cloud.githubusercontent.com/assets/14847553/13391012/fb8676bc-def7-11e5-83e4-3825998bc68f.png)

**Comment by vivek-addweb** [comment]
jQuery lib 'jquery.min.js' and 'jquery.js' both are called in this page. Pls remove 'jquery.min.js'

**Comment by Krina-Addweb** [comment]
Still displaying error :
![screen shot 2016-03-16 at 7 29 06 pm](https://cloud.githubusercontent.com/assets/14847553/13814727/68f2fb14-ebad-11e5-897a-98ae1f205dd2.png)
