### ISSUE TITLE
Username :

### ISSUE THREAD

**Issue by Krina-Addweb** [narendra-addweb/MyImmoPix#11]
1) After registering with new account & when logged-in into site first time user name is as shown https://www.evernote.com/l/Ag74TG0xPsdA7YSTwZboTXMQ2zWWAooHV6M/
2) After updating my-account (Firstname/Lastname), when I go to my-account page username is different from what I have earlier.https://www.evernote.com/l/Ag5g7jFWDq5EU6r45RL1L35JSWN3LhRKD8E
3) Lastly, when we are trying to login with updated username, it should allow us to login with that new credentials "

**Comment by narendra-addweb** [comment]
Resolved:

This issue might be with woocommerce old plugin and now this is resolved by plugin update process.
