### ISSUE TITLE
Recent order : Pay

### ISSUE THREAD

**Issue by Krina-Addweb** [narendra-addweb/MyImmoPix#114]
Pay from Recent order is not working with paypal, it redirect us on paypal but throws error.
![image](https://cloud.githubusercontent.com/assets/14847553/13457466/698a2310-e08e-11e5-935a-eb8581cd3a54.png)
![image](https://cloud.githubusercontent.com/assets/14847553/13457472/70b2f982-e08e-11e5-820a-df05d4fe028b.png)

**Comment by Maxfavier** [comment]
About Paypal, it had not been configured yet. It should lead to this account:

contact@lesphotographes.org

**Comment by narendra-addweb** [comment]
We are working over dev site and that's why I am using dummy paypal sandbox for testing purpose. 

You need to provide me your paypal sandbox credentials. I would make this setup once site is live. If you do not have paypal sandbox account, please create from [here](https://developer.paypal.com/docs/classic/lifecycle/sb_create-accounts).

**Comment by Maxfavier** [comment]
here are the credentials for the test account:
contact@myimmopix.com
addweb@123

**Comment by narendra-addweb** [comment]
Credentials are not working, can you please recheck. PFA screenshot for the same.

![paypal](https://cloud.githubusercontent.com/assets/15060303/13696598/6f099c7a-e78d-11e5-94cd-d16fc6e8fbb6.jpeg)

**Comment by Maxfavier** [comment]
Weird, these are the right credentials though. Password is addweb@123

Also cloned it to contact-1@myimmopix.com, same pass

**Comment by Maxfavier** [comment]
<img width="1246" alt="capture d ecran 2016-03-13 21 28 57" src="https://cloud.githubusercontent.com/assets/17143257/13731145/a39a17e0-e962-11e5-9cce-08a2aeecb405.png">

**Comment by Maxfavier** [comment]
<img width="681" alt="capture d ecran 2016-03-13 21 29 45" src="https://cloud.githubusercontent.com/assets/17143257/13731151/d0b99890-e962-11e5-929e-fa3a6d3552a8.png">

**Comment by Maxfavier** [comment]
I'm not sure on how this whole Paypal sandbox thing is working. If we don't get it to work, please give a me a Skype call and walk me through. Thank you

**Comment by narendra-addweb** [comment]
Credentials are working fine. Thanks!
