### ISSUE TITLE
Sign up :

### ISSUE THREAD

**Issue by Krina-Addweb** [narendra-addweb/MyImmoPix#12]
After registering new account from topbar "Sign Up" link, I received default wordpress mail with link which displaying in attached screen shot https://www.evernote.com/l/Ag67XRL6DhRFU7ZnxUvvewgZ3YhCV-4X3Yc is redirecting us on , it redirects me on set new password page , on that page New password should not be visible to user . see attached screenshot  
https://www.evernote.com/l/Ag5Cswu4_s5Az5yvg3JdJJ2oF9sNk_siTB4

**Comment by narendra-addweb** [comment]
Please check.

We use same page for registration process(My account page) so mail also comes from there with same detail.

**Comment by Krina-Addweb** [comment]
Sign up process is working fine from My account page as per above comment & for mail please see [this](https://github.com/narendra-addweb/MyImmoPix/issues/74) link
