### ISSUE TITLE
Final Order Summary : 

### ISSUE THREAD

**Issue by Krina-Addweb** [narendra-addweb/MyImmoPix#124]
Popup should not display all the time on the page reload.
![image](https://cloud.githubusercontent.com/assets/14847553/13568466/660cf878-e487-11e5-8e65-1fa6df297424.png)

**Comment by narendra-addweb** [comment]
I checked and noticed that popup is display bases on url action parameter. So this will always open until url contain 'action=done' parameter.

**Comment by saurabhd** [comment]
Add JS onclick and redirect user to dashboard.
