### ISSUE TITLE
Credit page: Label and cart content does not match

### ISSUE THREAD

**Issue by narendra-addweb** [narendra-addweb/MyImmoPix#129]
Label does not match with cart content.

![credit page- label doesnot match](https://cloud.githubusercontent.com/assets/15060303/13662849/7bb4645c-e6c3-11e5-905a-41e0a2caeff6.jpg)

**Comment by vivek-addweb** [comment]
@narendra-addweb 
I need to same number of <th> and <td> tag in table. Please maintain it.
