### ISSUE TITLE
Username :

### ISSUE THREAD

**Issue by Krina-Addweb** [narendra-addweb/MyImmoPix#13]
When we logged in with user & there is no Firstname & lastname added, at that time username should not be displaying blank value
https://www.evernote.com/l/Ag7VIH7PFbhNYalzuKIKWIa_6-v8SLrWC3c

**Comment by narendra-addweb** [comment]
Resolved:

Before change dropdown was display Firstname & Lastname at first but in case if both are not set then it was display blank. So we make changes here, If not set Firstname & Lastname then we display username string rather then leave blank.
