### ISSUE TITLE
Upload photos :

### ISSUE THREAD

**Issue by Krina-Addweb** [narendra-addweb/MyImmoPix#14]
Session for uploaded image from ""http://www.myimmopix.com/multiple-upload-en/"" when refresh page.

Scenario :
I have uploaded one image from http://www.myimmopix.com/multiple-upload-en/ and refreshes page.
Again I have uploaded another image and click on ""Next Step""
On next page, I am able to see previously uploaded image as well.

**Comment by narendra-addweb** [comment]
Not an issue:
As per my understanding this is correct because this is work as single project and that will display until user will either complete that order process OR delete that project.

In case this is wrong, please provide detail scenario how this work?
