### ISSUE TITLE
Cart sidebar: Remove quantity update functionality for every pages

### ISSUE THREAD

**Issue by narendra-addweb** [narendra-addweb/MyImmoPix#141]
Remove cart quantity increment '+' and decrement '-' buttons. Also quantity box make disable. After this change site user can't able to update his/her cart added credit bundle.

![cartsidebar](https://cloud.githubusercontent.com/assets/15060303/13897036/1d33cefc-edc8-11e5-9787-7e4dca7e24c6.jpg)

**Comment by narendra-addweb** [comment]
1. Deactivate 'WooCommerce Quantity Increment' plugin for remove increment/decrement buttons
2. Make quantity box disable

**Comment by Maxfavier** [comment]
What was the issue with the quantity increment ? How will the increment be organized then ? (for instance, if I want to buy 9 credits)
The cart does not look so good now, what is planned exactly ?

**Comment by saurabhd** [comment]
Hi Max,
This needs to be reverted. One thing I need to mention here about the current credit implementation, admin need to add the credit manually to user profile once payment is confirmed. Let me know if we are on same page or not.

**Comment by Maxfavier** [comment]
Hello,
The idea is not to have any input from the admin. The website store should attribute the right number of credits to the user's account - as they will be needed immediately to make an order.

This raises the question around the products, are they well defined in the site (woo commerce?) as to be able to adjust them eventually ?

**Comment by Maxfavier** [comment]
The design, as mentioned in issue #147 is a little off and should be adjusted to look more neat.
