### ISSUE TITLE
Remove Taxamo

### ISSUE THREAD

**Issue by Maxfavier** [narendra-addweb/MyImmoPix#142]
I had something installed for the management of VAT on the website called Taxamo
Jean-Charles, our inside dev, will install the payment modules soon.
Could this Taxamo be removed before hand ?

Thank you

**Comment by narendra-addweb** [comment]
Ok, we removed 'WooCommerce Taxamo' from [demo site](http://myimmopix.addwebprojects.com/).

**Comment by Krina-Addweb** [comment]
Failed due to there is some Language specific issue with paypal process.
