### ISSUE TITLE
payment module

### ISSUE THREAD

**Issue by Maxfavier** [narendra-addweb/MyImmoPix#149]
Dear all,

The payment module has been installed yesterday. A couple of things should be checked:
- Basket only fills in English. In other languages, total remains 0€ no matter what is in the basket.
- When going to the external payment plateforme (Monetico), when canceling the order, the credits are still added.

Thank you for checking this.

**Comment by Maxfavier** [comment]
[woocommerce-gateway-monetico-1.0.zip](https://github.com/narendra-addweb/MyImmoPix/files/208147/woocommerce-gateway-monetico-1.0.zip)

**Comment by saurabhd** [comment]
Hi Maxime,

We have checked the issue and it would take 6 hours to make it work. We need to patch the plugin code as it's not handling the case when user is canceling the order.

Thanks
Saurabh

**Comment by Krina-Addweb** [comment]
Please check following point which were done over myimmopix.addwebprojects.com :
1)When going to the external payment plateforme (Monetico), when canceling the order, the credits are still added.

**Comment by Maxfavier** [comment]
Hello, the credits are not added when canceling the order, so that's good, but there are several bugs.

Before going to the Monteico platform, there is a "debug mode" part on the screen.

![capture d ecran 2016-04-14 08 28 36](https://cloud.githubusercontent.com/assets/17143257/14518895/8626b764-021b-11e6-96fd-4e8afb94471c.png)

Back from the bank platform after cancellation, we get first this screen:
![back from order 1](https://cloud.githubusercontent.com/assets/17143257/14518914/a4f6f7a8-021b-11e6-801b-a129c2fccdb9.png)

Then, the page where we arrive a has a display bug when scrolling.
![beck from order 2](https://cloud.githubusercontent.com/assets/17143257/14518927/b492672e-021b-11e6-8e54-75a5f107a2ee.png)

**Comment by narendra-addweb** [comment]
Debug mode was enabled due to development is in progress, the error shown in second screen grab is due to the email server issue and will be resolved once we go live.

**Comment by Maxfavier** [comment]
Ok, perfect.
What about the language issue?

> - Basket only fills in English. In other languages, total remains 0€ no matter what is in the basket.
