### ISSUE TITLE
Text issue after payment

### ISSUE THREAD

**Issue by Maxfavier** [narendra-addweb/MyImmoPix#151]
I've tried to work out the payment using Monetico, everything is OK.
Except after coming back from the payment platform as the text that is written under the green confirmation box is saying that payment didn't work although it did work.
See attachment A
However if I reload the page, the proper text is available see attachment B.
_(on these print screen, order number is different as it was taken from two different orders showing the same)_

I tried in French but I suppose to observe the same in other languages.

URL where problem was seen: http://www.myimmopix.com/fr/validation-2/order-received/71868/?key=wc_order_57160f8f25aef&utm_lang=selector

<img width="1243" alt="attachment a" src="https://cloud.githubusercontent.com/assets/17143257/14637562/5a918f6e-0632-11e6-88a8-25941e784bb1.png">
<img width="1213" alt="attachment b" src="https://cloud.githubusercontent.com/assets/17143257/14637563/5ab006ce-0632-11e6-9ffe-413368acbe56.png">

**Comment by narendra-addweb** [comment]
I require CIC card details(Card number, Expire date and verification code) for re-generate case.

**Comment by Maxfavier** [comment]
I cannot provide this information unfortunately. Any card will do actually. 
Tell me if there is another possibility to regenerate this.

**Comment by narendra-addweb** [comment]
I reviewed and found, the issue with 'Monetico' payment gateway and wooCommerce order complete status hook. I require admin access and FTP for check this issue solution over live site.

Please approve so we can use dummy ​_American Express​_ card number at live server for testing.

**Comment by Maxfavier** [comment]
I'll get back to you on the Skype channel where Sylvain can also see the exchanges.

**Comment by Maxfavier** [comment]
www.myimmopix.com
Admin username: Ashish | Password: FUNCARj@xsZX*RZlH1vZj4Jm

FTP access:
Host : 94.23.29.176
Port : 2221
User : AWS
Password : +7(^?z[&_4?a=tB

**Comment by narendra-addweb** [comment]
Please check, 

Hours consuming this task: 2.5 Hrs 

As without card credential, I can't able to re-generate/test this change with 'Monetico' so please check and let me know if any issue.

Additionally please update 'PayPal Email' and 'Receiver Email' field into '**Admin > WooCommerce > Checkout > Paypal**' with your live paypal account email address. 

Currently we are use your given '_contact@myimmopix.com_' for testing.

**Comment by Maxfavier** [comment]
I've given it a try and it works perfect.
Thank you.

I'll look up for the Paypal setup.
