### ISSUE TITLE
Design after payment

### ISSUE THREAD

**Issue by Maxfavier** [narendra-addweb/MyImmoPix#152]
Some blue lines are visible on the green box after payment, see attachment.

<img width="1261" alt="capture d ecran 2016-04-19 13 02 26" src="https://cloud.githubusercontent.com/assets/17143257/14637600/b5549360-0632-11e6-9113-2a43aef5bf22.png">

**Comment by Krina-Addweb** [comment]
1) Suggestion : Should we center align this message "Thank you. Your order has been received."
2) We have removed the vertical blue line shown above over demo site.

**Comment by Maxfavier** [comment]
1) yes you can align, indeed.
2) Thanks

--> possible to implement in the live site directly ?

**Comment by narendra-addweb** [comment]
Please check, Changes done over demo server http://myimmopix.addwebprojects.com.

As I have no FTP access for _wp-content/themes_ folder to transfer updated files over live. So I attache these file with _readme.txt_ in zip  format. Please find attached [GIT-152.zip](https://github.com/narendra-addweb/MyImmoPix/files/229335/GIT-152.zip)

Please follow _readme.txt_ instruction and let me know if there is any concern.

**Comment by Maxfavier** [comment]
Thanks!
