### ISSUE TITLE
Regulation about cookies

### ISSUE THREAD

**Issue by narendra-addweb** [narendra-addweb/MyImmoPix#154]
The law imposes that we prevent the users that our site uses cookies, thus a bar should be placed up (or bottom, according to best design) on the site as such:

![cookie](https://cloud.githubusercontent.com/assets/15060303/14786605/53154e8e-0b1d-11e6-8c54-bbf3d0822077.jpeg)

_Text in FR:_
Ce site utilise des cookies pour vous offrir le meilleur service. En poursuivant votre navigation, vous acceptez l'utilisation des cookies de ce site.

_Text in ENG:_
This website uses cookies to ensure a smooth service. By further browsing you accept using the cookies of this website.

**Comment by narendra-addweb** [comment]
**Cookie lifetime & workflow**
Set cookie life time for 15 day. After 15 from cookie create cookie will auto delete. After delete this cookie(Name 'aws_visited') again notification popup will show for same as open at first time.

**Settings**
This plugin "_Cookie popup_" support multi-language message popup functionality. Additionally you can change notification position(Top/Bottom) from _Admin > Settings > Cookie Popup_ page.

**Comment by Maxfavier** [comment]
Do I understand that there's a plugin to install in the live version ?

**Comment by Maxfavier** [comment]
Let me know the download link if I'm supposed to do it.

**Comment by narendra-addweb** [comment]
Please find [aws-cookie-popup.zip](https://github.com/narendra-addweb/MyImmoPix/files/238135/aws-cookie-popup.zip) and upload at live server(www.myimmopix.com).

**Steps to use plugin**
1) Unzip _aws-cookie-popup.zip_
2) Upload '_aws-cookie-popup_' directory to your '_/wp-content/plugins_' directory
3) Go to the plugin management page and enable the **Addweb Cookies Popup**.
4) Browse to _Settings > Cookie Popup_
5) Customize your cookie notification message with active language(s) and popup display position(Top/Bottom) for site.

Let me know if there is any confusion. Thanks!
