### ISSUE TITLE
Our Services : Spelling mistake 

### ISSUE THREAD

**Issue by Krina-Addweb** [narendra-addweb/MyImmoPix#157]
There is a spelling mistake in Content which is displayed in attached screenshot for Our service section, which was placed from the following document.(https://docs.google.com/spreadsheets/d/1CAqlUOdJIH0JMQ7g_az8XmgpMsagmlRTaaJwaobk914/edit#gid=1222378017)
![image](https://cloud.githubusercontent.com/assets/14847553/14845292/da37f28c-0c7a-11e6-96df-b4873c9c772b.png)

**Comment by narendra-addweb** [comment]
@maxime Please find [GIT-157.zip](https://github.com/narendra-addweb/MyImmoPix/files/238329/GIT-157.zip) and replace '_home-services.php_' file under _'wp-content/themes/adrenailn/_' path.

Above file contain spell correction change for 'adgustment' correct is 'adjustment'.

Let me know if there is any confusion. Thanks!
