### ISSUE TITLE
Upload photos : Choose photo

### ISSUE THREAD

**Issue by Krina-Addweb** [narendra-addweb/MyImmoPix#16]
When we click on Choose photo & select any other file format than image file format ,it should not upload it & throws a validations for that.
https://www.evernote.com/l/Ag7cl1lTkgFLq6Z4NbUQUrlAeA-dtVrf4Io

**Comment by narendra-addweb** [comment]
Please check:
I just allow graphical files only(Viz. jpeg, jpg, bmp, gif, png, ico) for now, let me know if require more types for allow to upload.

**Comment by Krina-Addweb** [comment]
Right now it allows us  to upload only .jpeg file extension, other file format (Valid extension(s): jpg,  bmp,  gif,  png,  ico.) with upload is not working. 
![screen shot 2016-02-12 at 1 51 47 pm](https://cloud.githubusercontent.com/assets/14847553/13001850/dbecf1d4-d18f-11e5-90c5-ccd799592478.png)

**Comment by Krina-Addweb** [comment]
Now above all image file formats are properly worked with the Photo uplodation process.
