### ISSUE TITLE
Footer Company link pages issues : 

### ISSUE THREAD

**Issue by Krina-Addweb** [narendra-addweb/MyImmoPix#163]
Following are the existing issues for Company Link pages : 
1)About us : 

1) Need to design title like OUR HISTORY,Key Features Consistently
2) Dummy Content
3) Latest News section issue for all languages 
4) Inner page of news :  Leave reply comment section's Mandatory fields
5) businessees typo “businesses”
6) Inner page Comment is not working, after comment it redirect us on page not found.
7) Loved by over 1,000 people worldwide section content alignment
8) For Multi language repeated Content issue.

2)Privacy policies : 

1) Maxime Favier operates h?ttp://www.myimmopix.com the “Site”) Website address & starting ( is missing.

3)Terms & Condition

1) Remove Extra gap from desc.
2) Highlight The title of Terms & conditions points
3) Desc. is some how looks like missing
4) Language Key features points & latest news section

Note : 
1) Please provide multi language content for below pages.
2) For Responsive issues regarding Footer pages are mentioned in Git #160 which is created for all responsive issues.
3) I assume that there is no need for a sliders over About us page & Contact us page, so what should we have to do for the sliders in both the pages.

**Comment by Maxfavier** [comment]
Confidentiality + About us + terms& conditions (multilingual)

Please use this updated content.

[Privacy policy CGV MIP.docx](https://github.com/narendra-addweb/MyImmoPix/files/263017/Privacy.policy.CGV.MIP.docx)

**Comment by Maxfavier** [comment]
Also here are the links for Facebook page and twitter:
https://www.facebook.com/myimmopix/
@myimmopix

You can remove Pinterest, g+ and RSS.

Although you could also link a blog down there: www.photos-immobilier.com

**Comment by Maxfavier** [comment]
3/ You can indeed remove the slide on the contact page and about us page.

**Comment by Krina-Addweb** [comment]
**All**
Functionality and content 
1)In About us page slider should not visible while language is dutch/french.
2)About us “www.thephotoacademy.com"  link is not working. while language is Eng/Dutc
3)In About us page Passage in French language should align properly.
4)In Term and conditions Remove extra space between prix section both sentences for french.
5)In Term and conditions Link “myimmopix” is not display Commande,Clause de rétractation section in french.
6)In privacy policy Defination title should display in next line. According Document. check for eng and french.
7)In Privacy policy Data collected section should display properly remove extra space,use bullets which is displayed in document check for eng and french.
8)In Privacy Policy "available via the link below : https://www.monetico-paiement.fr/fr/securiser-transactions/garanties-securite.html" these whole line is missing form data collected section check for eng and french.
9)In privacy policy Collected Computer Data Section should Align properly use bullets according to documentation. and Cookies Section should align properly and use bold for 'cookies' title check for eng and french.
10)In privacy policy Www.Myimmopix.com When click on link it display that 'oops page is not found' check for eng and french.

Suggestion :-
1)About us page If We Change language then it should change about us title in french language.
2)In Privacy page Title Should Return as "Privacy policy” not as "Privacy"
