### ISSUE TITLE
Contact us :

### ISSUE THREAD

**Issue by Krina-Addweb** [narendra-addweb/MyImmoPix#164]
Can you please provide us the mail content for Contact us.

**Comment by Maxfavier** [comment]
For Contact us page.

Location should be as follows:

ENG:
Myimmopix.com
A **Les Photographes Organisation** brand
19, quai de la Seine,
75019 Paris
France

T: +33 1 82 88 48 83
E: info@myimmopix.com

FR:
Myimmopix.com
Une marque **Les Photographes Organisation**
19, quai de la Seine,
75019 Paris
France

T: +33 1 82 88 48 83
E: info@myimmopix.com

NL: as for ENG

---

In addition, the "contact us" link should be added in footer in the "company section".
"contact us" = "Nous contacter" in FR

---

Translation ENG to FR (keep same as ENG for NL)

Your Name (required) = Votre nom (requis)
Your Email (required) = Votre email (requis)
Your Company = Votre entreprise
Telephone Number = Numéro de téléphone
Your Message = Votre message

---

Could you check how the slider shown this page ? (I have some issues with Chrome)

---

Should there be a captcha of some sorts to avoid spamming?

Thanks you

**Comment by narendra-addweb** [comment]
Hi Maxime,

**1)** For Contact us page. Location should be as follows:

> Done

**2)** In addition, the "contact us" link should be added in footer in the "company section". "contact us" = "Nous contacter" in FR

> Done

**3)** Translation ENG to FR (keep same as ENG for NL)

> Done

**4)** Could you check how the slider shown this page ? (I have some issues with Chrome)

> Will remove slider for " contact page and about us page"

**5)** Should there be a captcha of some sorts to avoid spamming?

> For captcha, We can use reCAPTCHA from Google’s service. And for that you need a Google account and to register your site for an API key pair.
> After generate that API key pair, provide me so I can active it over site and use reCAPTCHA. For more detail, please refer http://contactform7.com/recaptcha.

Further I would require email format you would prefer. Here's the example provided: 

To:             contact@myimmopix.com
From:           [Your name] contact@myimmopix.com
Subject:            MyImmopix: Contact inquirey
Message Body:   

From: [Your Name] <[Your Email]>
Your Company: [Your Company]
Telephone Number: [Telephone Number]

Message Body:
[Your Message]

Sincerely yours,
Myimmopix - The team

Thanks!

**Comment by Maxfavier** [comment]
1/2/3/ --> Thanks
4/ --> OK
5/ Site key: 6LdDGyATAAAAAEzxXqhJG3SbG1Ze411S3H1xNr8E

About the mail, can you specify what is needed exactly ?
Is that the email we'll receive from the contact page ? 
(it should read "inquiry" and not "inquirey" in email subject)

**Comment by narendra-addweb** [comment]
Hi Maxime,

Please provide reCAPTCHA Secret key as well.

Thanks!

**Comment by Maxfavier** [comment]
![capture d ecran 2016-05-17 09 05 35](https://cloud.githubusercontent.com/assets/17143257/15391345/e95a3444-1dc0-11e6-9f85-dee4dd72d09b.png)

**Comment by Maxfavier** [comment]
6LdDGyATAAAAALMVQ9k2MJusHH02UQvqarrVvkhr
