### ISSUE TITLE
Contact us :

### ISSUE THREAD

**Issue by Krina-Addweb** [narendra-addweb/MyImmoPix#17]
On click on send button nothing is happen, field validations are missing & form should be submit.

**Comment by narendra-addweb** [comment]
Please check.

**Comment by Krina-Addweb** [comment]
Contact form should submit on click on the SUBMIT button, right now nothing is happening only one loader is running continuously below the submit button.

**Comment by narendra-addweb** [comment]
This is server related issue. So skip it for demo server. Please check it after go live.

**Comment by Krina-Addweb** [comment]
As if now we were adding a dummy content so skip it now.
