### ISSUE TITLE
Contributor,Editor :

### ISSUE THREAD

**Issue by Krina-Addweb** [narendra-addweb/MyImmoPix#19]
Upload photos link missing from navigation bar. https://www.evernote.com/l/Ag7J5hR2MnBPPIqEflzmCqbdNAMi0h4x0Xs

**Comment by narendra-addweb** [comment]
Not reproduced:
I unable to reproduce it, please provide some case here so I can see that.

**Comment by Krina-Addweb** [comment]
When logged in with Contributor/Editor user role "Upload Photo" link should be display. 
Right now it is not displaying( Check it with both the site). See attached screenshot.

![9ba870bc-43d0-42db-bc83-569796d9e3be](https://cloud.githubusercontent.com/assets/14847553/13000931/909cc0be-d186-11e5-9969-c149146aa547.png)

**Comment by narendra-addweb** [comment]
We moved this to header menu section.

**Comment by Krina-Addweb** [comment]
As we fix all header links, now the links were displayed to all user roles same
