### ISSUE TITLE
Translation issues :

### ISSUE THREAD

**Issue by Krina-Addweb** [narendra-addweb/MyImmoPix#23]
**English :**

Menu :  1) FAQ is missing from menu
             2) Terms & Conditions are missing
             3) Privacy & policies page is missing
Upload: 2) Or upload more photos` instead of or upload more photos.
Buy Credit : 3) In credit page "Purchase more credits"

**French :**

Menu : 1) Translate Example into france ""Exemples""
            2) There is a typo in ""Tariff"" change it to ""Tarifs"""
Order summary : "1)Translate ""Necessary credits"" to ""Crédits nécessaires""
                             2)Translate ""Credits available "" to ""Crédits disponibles"""
Buy Credit : "1)Translate ""Purchase credit"" to ""Acheter des crédits supplémentaires""
                     2)Translate """"One credit"""" to """" Un crédit""""
                     3)Translate """"View cart"""" to """" Voir le panier""""
                     4)Translate """"Check Out"""" to  """"Commande""""
                     5)Translate """"Prices excluding taxes"""" to """"Prix hors TVA"""""""
Cart    :  1) Translate ""One credit"" was successfully added to your cart to ""Un crédit"" a 
           été ajouté à votre panier
           2) Translate ""Your credit"" to ""Vos crédits"""
Icon :  1)Translate "Dust clean up" to "Suppression des défauts"

**Nederlands :**

Menu : 1)Translate ""Example"" to ""Voorbeelden""
            2)Translate ""Pricing"" to ""Tarieven"""
Project list : 1)Translate "Project list" to "Lijst projecten"
                2)Translate "One credit" to "1 krediet" instead of "een credit"
                3)Translate "Your credit" to "Uw kredieten" instead of "
Tour : 1)Translate "Create a free account" to "Creëer een account" instead of "Creer een account"

**Comment by narendra-addweb** [comment]
**English** 
Menu :
1) FAQ is missing from menu

> Added into footer
> 2) Terms & Conditions are missing
> Added into footer
> 3) Privacy & policies page is missing
> Added into footer

Buy Credit : 
3) Buy Credit : In credit page "Purchase more credits"

> Not exist into credit page

**French**
Buy Credit:
3)Translate """"View cart"""" to """" Voir le panier""""

> Not exist into credit page
> 5)Translate """"Prices excluding taxes"""" to """"Prix hors TVA"""""""
> Not exist into credit page

Cart :
1) Translate ""One credit"" was successfully added to your cart to ""Un crédit"" a
été ajouté à votre panier

> Comes from wooCommerce plugin
