### ISSUE TITLE
Menu :

### ISSUE THREAD

**Issue by Krina-Addweb** [narendra-addweb/MyImmoPix#24]
When we click on either PRICING,TOUR or OUR SERVICES it should redirect or focused that area properly, right now, which is not working correctly For ex.: see the attached screenshot for pricing.
https://www.evernote.com/l/Ag6dFDa6oGxDy7Gq2TBAAW8lyFLtDLghvaU

**Comment by narendra-addweb** [comment]
Duplicate with > Home Page : Menu #26

**Comment by Krina-Addweb** [comment]
Not working correctly, please recheck it.

**Comment by Krina-Addweb** [comment]
This is is marked as Duplicate with Home Page : Menu [#26 ](https://github.com/narendra-addweb/MyImmoPix/issues/26)
