### ISSUE TITLE
Home Page : Menu 

### ISSUE THREAD

**Issue by Krina-Addweb** [narendra-addweb/MyImmoPix#26]
Need for smooth scrolling redirection when we click on  either PRICING ,TOUR or OUR SERVICES.

**Comment by narendra-addweb** [comment]
Please check:
We add JQuery code for smooth scrolling.

**Comment by Krina-Addweb** [comment]
Not working correctly, please recheck it.

**Comment by Maxfavier** [comment]
It's not really smooth at this moment.
I also notice that "Example" leads to another page, while it could just link to the example section below, just like "Pricing", "Tour" and "Our services" do.

**Comment by narendra-addweb** [comment]
Please check.

**Comment by Krina-Addweb** [comment]
Scrolling is still not smoothly working, please recheck it.
