### ISSUE TITLE
Menu 

### ISSUE THREAD

**Issue by Krina-Addweb** [narendra-addweb/MyImmoPix#27]
Menu links are missing from all inner pages

**Comment by narendra-addweb** [comment]
Not an issue:
There is are different menu(s) for inner pages and home page and that's why both menus are display different.

**Comment by Krina-Addweb** [comment]
Need to solve this issue please check it again.

**Comment by Krina-Addweb** [comment]
Header links are there in all inner pages, but EXAMPLE, PRICING, TOUR, & OUR SERVICES links are not working at all.It should redirect us on the homepage with a proper focus on that particular section.
