### ISSUE TITLE
Buy Credits

### ISSUE THREAD

**Issue by Krina-Addweb** [narendra-addweb/MyImmoPix#3]
Need to remove buy credits link from the header of inner pages.
https://www.evernote.com/l/Ag69CGGcqBxDMIwpUW2BVz8tRwyzwdaw_FU

**Comment by narendra-addweb** [comment]
Not an issue:

This is not a simple link, this is announcement content which are comes from _Admin > Announcement page_ and that's why this is not an issue

**Comment by Krina-Addweb** [comment]
Ok, that makes sense if it is announced.

**Comment by Maxfavier** [comment]
I still see it in some the inner pages, but as it is not an issue, I can close this one ?

**Comment by narendra-addweb** [comment]
From now we set a general menu for every page so you can close.
