### ISSUE TITLE
Home Page: START

### ISSUE THREAD

**Issue by Krina-Addweb** [narendra-addweb/MyImmoPix#4]
Need to clear the START Functionality without login.

**Comment by narendra-addweb** [comment]
Without login, _START_ link display on top header in red color. Once you click on that _START_ link then user will redirect on _MY ACCOUNT_ page for login/register. Once user login then user will redirect on _UPLOAD PHOTOS_ page. But if user create new account by fill up _Register_ form and complete that process then he/she will redirect on _MY ACCOUNT_ page.
