### ISSUE TITLE
PDF Homepage T.A.c:

### ISSUE THREAD

**Issue by Krina-Addweb** [narendra-addweb/MyImmoPix#43]
T.A.c: Alignment of the header should be reworked, see examples.
![image](https://cloud.githubusercontent.com/assets/14847553/12970809/761a3db6-d0b9-11e5-9fe6-31f5987f7aff.png)
"Start" uses the main red, and leads to the "upload photos" page. When uploading, a
signup/login will be then asked.

**Comment by Maxfavier** [comment]
Ok for this part, but we should add a sentence above login/setup on the page. See attachment (I also increased a little the spacing between the blue title line and the login/setup blocs.
![capture d ecran 2016-02-17 18 12 58](https://cloud.githubusercontent.com/assets/17143257/13118076/d69ab66e-d5a2-11e5-82ea-094127987bbc.jpg)
