### ISSUE TITLE
Multiple VAT fields exist

### ISSUE THREAD

**Issue by narendra-addweb** [narendra-addweb/MyImmoPix#48]
There are multiple VAT fields exist with different label and validation functionality. 
 ![checkout_vat_fields](https://cloud.githubusercontent.com/assets/15060303/12971166/e1927136-d0bd-11e5-9627-da0f33f853fa.jpeg)

**Comment by Maxfavier** [comment]
This is a relic from the previous team. There should be a single VAT number, starting with the 2 letters of country code (i.e. BE0123456789). This is a EU number

**Comment by narendra-addweb** [comment]
Thanks for the update

**Comment by narendra-addweb** [comment]
If user wants to exempt of VAT then he/she need to fill EU VAT number.

**Comment by Maxfavier** [comment]
I can not yet check this point ss I can not find a link to the shop.
It makes me think that an action button might miss on the home page in the Pricing section. Something like a "buy credits" red button.
What do you think ?
