### ISSUE TITLE
Registration :

### ISSUE THREAD

**Issue by Krina-Addweb** [narendra-addweb/MyImmoPix#5]
Content :: When user receive registration mail, there is need to change the text that says "You can access your account area to view your orders and change your password here after logging into site."

https://www.evernote.com/l/Ag5rTC51jj9H1p39Z2KujoAgebGFTStWJX0

Functionality:: When we create user with yahoo mail id , direct link with (You can access your account area to view your orders and change your password here: http://www.myimmopix.com/my-account) is not created or displayed.
https://www.evernote.com/l/Ag5rTC51jj9H1p39Z2KujoAgebGFTStWJX0

**Comment by narendra-addweb** [comment]
**1**. Content is proper as per the functionality. 
**2**. Link issue is from Yahoo. Please check for more [Email hyperlinks not working in yahoo email?](https://in.answers.yahoo.com/question/index?qid=20110907140149AAiYtbm)
