### ISSUE TITLE
PDF Footer T.B.a: 

### ISSUE THREAD

**Issue by Krina-Addweb** [narendra-addweb/MyImmoPix#56]
Change design as follows:
![image](https://cloud.githubusercontent.com/assets/14847553/12971632/50625428-d0c3-11e5-9f80-0169b7534f08.png)
![image](https://cloud.githubusercontent.com/assets/14847553/12971646/6bb093ac-d0c3-11e5-80b9-b91b293f4ed8.png)

**Comment by Krina-Addweb** [comment]
See the attached misaligned things for failed status.
![image](https://cloud.githubusercontent.com/assets/14847553/13747611/1669991e-ea1f-11e5-9c3c-b2c2cbafdd42.png)

**Comment by Maxfavier** [comment]
Footer's color should be #333333 (I see now #171717).
