### ISSUE TITLE
PDF UPLOAD PHOTOS T.C.a & T.C.b 

### ISSUE THREAD

**Issue by Krina-Addweb** [narendra-addweb/MyImmoPix#57]
1) Take out the "buy" credits next to the logo
2) Take out the "Better photos, better sales !". The catch phrase should be the one defined 
in 1/ and positionned the same way.

**Comment by narendra-addweb** [comment]
Removed "Buy now"(Announcement) functionality and "Better photos, better sales !".

From now, header menu is general for all pages.

**Comment by Krina-Addweb** [comment]
Its done but header link manage projects is over lapped on dropdown
![image](https://cloud.githubusercontent.com/assets/14847553/13078600/22c30c3e-d4e6-11e5-907a-e034a392c47b.png)
