### ISSUE TITLE
PDF UPLOAD PHOTOS T.C.c

### ISSUE THREAD

**Issue by Krina-Addweb** [narendra-addweb/MyImmoPix#58]
The "Upload Photos" and "My projects" should be brought in the header, at the place of 
"better photos, better sales". Alignment of items in this header should be based on the same 
principle as seen in task [T.A.d.](https://github.com/narendra-addweb/MyImmoPix/issues/44)

**Comment by narendra-addweb** [comment]
Removed "Better photos, better sales !" and place "Upload Photos" and "My projects".
From now, header menu is general for all pages.
