### ISSUE TITLE
PDF UPLOAD PHOTOS T.C.d

### ISSUE THREAD

**Issue by Krina-Addweb** [narendra-addweb/MyImmoPix#59]
After loading the images, the following screen appears. There should be more space
under the images uploaded. The images should be smaller as well.
There shouldn't be so much space between the "CHOOSE PHOTOS" and the "Next step >>"
"Next step" should be brought into capital letters.
Ideally, the button should have the same width as the "CHOOSE PHOTOS" one.
![image](https://cloud.githubusercontent.com/assets/14847553/12971822/28e330c8-d0c5-11e5-9d4a-8643169862c7.png)

**Comment by Maxfavier** [comment]
Issue is solved, however the "Choose photos" sends me error after a first upload (see attachment).

We might as well take off the "Choose photos" and link the "upload more photos" text towards the uploader. It might make more sense.
<img width="953" alt="capture d ecran 2016-02-18 13 31 43" src="https://cloud.githubusercontent.com/assets/17143257/13143559/fd9899fa-d644-11e5-8bc1-189bb38219df.png">

**Comment by Maxfavier** [comment]
I agree strongly. It will also save space and optimize the design.

**Comment by Maxfavier** [comment]
As mentionned over Skype: after the first upload of images, the screen should be as such: 
("choose photos" is removed, and the "upload more photos" is linked to do the same as "choose photos" (add more pics to the same project).

![capture d ecran 2016-03-01 15 35 33b](https://cloud.githubusercontent.com/assets/17143257/13430173/3ee00df2-dfc4-11e5-8d28-a2460889bcfe.jpg)

**Comment by Maxfavier** [comment]
In terms of design, the "next step" button should end up where the "choose photos" was.
