### ISSUE TITLE
PDF PROJECT DETAIL T.D.a:

### ISSUE THREAD

**Issue by Krina-Addweb** [narendra-addweb/MyImmoPix#60]
After pressing "next step" on the upload photos page, we reach the "project detail page.
In the bluebox, the word "Uploaded" is missing before the timing. In the example below,
it should thus be: "Uploaded 00:08:43 ago".
If possible, this time should be in the format "Uploaded 9 minutes ago" or "Uploaded 12 hours 
ago" or "Uploaded 3 days ago", using rounded up or down approximations.
![image](https://cloud.githubusercontent.com/assets/14847553/12971844/6d869e72-d0c5-11e5-8884-af4a00c6da62.png)

**Comment by narendra-addweb** [comment]
From now it display as per below:

> Uploaded 9 minutes/hours/days/months/years ago

**NOTE**: We make same changes in _PRODUCT DETAIL_ as well _PROJECT DETAIL_ to maintain consistency

**Comment by Krina-Addweb** [comment]
Need to change "Uploaded 55 min ago" to  "Uploaded 55 minutes ago"
