### ISSUE TITLE
PDF ORDER SUMMARY T.E.a:

### ISSUE THREAD

**Issue by Krina-Addweb** [narendra-addweb/MyImmoPix#62]
Check the graphics on the bullets for selection editing/no editing, it's not perfect.
Also suggest a graphical improvement to this as it is quite out dated way of selection.
![image](https://cloud.githubusercontent.com/assets/14847553/12971875/df04f74c-d0c5-11e5-9096-14ebf5744d19.png)

**Comment by Maxfavier** [comment]
Thank you. Could we change the texte "Editing : 1 Credits" to "Editing (1credit)
