### ISSUE TITLE
Buy Credit: General issue

### ISSUE THREAD

**Issue by narendra-addweb** [narendra-addweb/MyImmoPix#65]
1) Message "Your cart is currently empty" should be display in proper manner
2) "Please login to buy credit", word _login_ should design with login link
3) _RETURN TO SHOP_ button should not display if user not logged in
![buy_credit_issue1](https://cloud.githubusercontent.com/assets/15060303/12999407/aa8eedb0-d174-11e5-927d-9012b05141dd.jpeg)

**Comment by Krina-Addweb** [comment]
Done, but make a consistent spelling of "Login" either make it "Log in" or "Login" for whole site.
**
![image](https://cloud.githubusercontent.com/assets/14847553/13212404/0e7267f4-d967-11e5-9dec-bfcab0fb7361.png)

**
![image](https://cloud.githubusercontent.com/assets/14847553/13212458/6711b55e-d967-11e5-9ea6-672b2af0031e.png)
