### ISSUE TITLE
Buy Credit: Design issue

### ISSUE THREAD

**Issue by narendra-addweb** [narendra-addweb/MyImmoPix#66]
On Credit page, Login/Register popup and page design mismatched.
![buy_credit_issue_2](https://cloud.githubusercontent.com/assets/15060303/12999452/3a4c578a-d175-11e5-9e49-eb9f6d1cdc51.jpeg)

**Comment by Krina-Addweb** [comment]
Issue need to resolve again,it is still not perfect.
![screen shot 2016-02-18 at 3 39 54 pm](https://cloud.githubusercontent.com/assets/14847553/13140137/40ff4084-d656-11e5-8dc3-d43eb02a1ae4.png)
