### ISSUE TITLE
Contact Us page

### ISSUE THREAD

**Issue by Krina-Addweb** [narendra-addweb/MyImmoPix#70]
1) Remove this effect from contact us page:,
![image](https://cloud.githubusercontent.com/assets/14847553/13001279/368dabf2-d18a-11e5-80a4-79a538c27b5b.png)
2) Need to design a validation error message at the top of contact form & also Focus on fields with errors were missing.
![image](https://cloud.githubusercontent.com/assets/14847553/13001300/670b287c-d18a-11e5-9864-80b93c6dbbdc.png)

**Comment by narendra-addweb** [comment]
1) As we check not able reproduce.
2) Change message position from bottom to top of the form

**Comment by Krina-Addweb** [comment]
Ok that issue was occurred due to one addon, now its working fine thanks.
