### ISSUE TITLE
Contact us:

### ISSUE THREAD

**Issue by Krina-Addweb** [narendra-addweb/MyImmoPix#71]
Contact us form is not submitted & when we click on console it fires
Warning: stream_socket_enable_crypto(): SSL operation failed with code 1. OpenSSL Error messages: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed in wp-includes/class-smtp.php on line 344
{"mailSent":false,"into":"#wpcf7-f70678-p1928-o1","captcha":null,"message":"Failed to send your message. Please try later or contact the administrator by another method."}

**Comment by narendra-addweb** [comment]
This issue is due to server settings, once we setup this on live server we will check for that.
