### ISSUE TITLE
Review project page 

### ISSUE THREAD

**Issue by Krina-Addweb** [narendra-addweb/MyImmoPix#75]
When we click on (X) to remove the photo, uploaded photos should be removed from the list, right now one loader is continuing moving.
![image](https://cloud.githubusercontent.com/assets/14847553/13027328/a82532f8-d270-11e5-9a5e-e2f438a4cb7f.png)

**Comment by narendra-addweb** [comment]
This issue is due to server settings, once we setup this on live server we will check for that.
