### ISSUE TITLE
Manage projects :

### ISSUE THREAD

**Issue by Krina-Addweb** [narendra-addweb/MyImmoPix#79]
Need to remove following errors from the page
![image](https://cloud.githubusercontent.com/assets/14847553/13105823/0dd7d4bc-d58b-11e5-9cfc-d12da20c5d49.png)

**Comment by Maxfavier** [comment]
Similar errors found (as mentioned in another closed issue as well)
<img width="1161" alt="capture d ecran 2016-02-19 08 45 39" src="https://cloud.githubusercontent.com/assets/17143257/13169388/570d0638-d6e5-11e5-88f7-c8caf6a66213.png">
