### ISSUE TITLE
Edit My account: Email

### ISSUE THREAD

**Issue by Krina-Addweb** [narendra-addweb/MyImmoPix#8]
When we use exist email address on update of email address, it should validate user that email address already exists.

**Comment by narendra-addweb** [comment]
Not reproduced on live:
Steps:
1) I use _johnnyharpertesting1@gmail.com_ email and go to my account for change it.
2) Replace email with existing on(_johnnyharpertesting2@gmail.com_)

And it validate that **This email address is already registered.**. 
So this is not an issue.
