### ISSUE TITLE
Product detail: photo count display mismatch

### ISSUE THREAD

**Issue by narendra-addweb** [narendra-addweb/MyImmoPix#81]
If I removed uploaded photo then photo removed but count not changed correspond number of photo(s).

![count not changed](https://cloud.githubusercontent.com/assets/15060303/13136639/53c2d9fc-d641-11e5-87bd-ab4f9560a6ad.jpeg)

**Comment by narendra-addweb** [comment]
Resolve static count issue on AJAX delete functionality. 
Also X Photos, here Photos is not multi language supported so set this also.

**Comment by Krina-Addweb** [comment]
Not working correctly, when we delete or remove any uploaded photo at that time still loader moving continuously & also count is not updated on refresh also.

**Comment by narendra-addweb** [comment]
This issue is due to server settings, once we setup this on live server we will check for that.
