### ISSUE TITLE
Upload Photos:

### ISSUE THREAD

**Issue by Krina-Addweb** [narendra-addweb/MyImmoPix#82]
Need to have some space below the project detail steps.
![image](https://cloud.githubusercontent.com/assets/14847553/13140328/51d3903a-d657-11e5-9b8d-966f93336a10.png)

**Comment by Maxfavier** [comment]
I close the issue. However I there are some issues to view the projects.
<img width="710" alt="capture d ecran 2016-02-19 08 43 22" src="https://cloud.githubusercontent.com/assets/17143257/13169325/f06d2ea8-d6e4-11e5-8d6b-392ea735f79a.png">

**Comment by narendra-addweb** [comment]
This issue is due to location of old project images are changed. This issue would not appear over live.

**Comment by saurabhd** [comment]
#79
