### ISSUE TITLE
Homepage : Main Slider

### ISSUE THREAD

**Issue by Krina-Addweb** [narendra-addweb/MyImmoPix#89]
1) Link is missing from the slider button, it should redirect us on http://adrenalin.captivate.io/shop/ 
![image](https://cloud.githubusercontent.com/assets/14847553/13248742/248462b0-da46-11e5-8677-c34edeb849db.png)
2) When we click on this slider button (displayed in below screenshot) it should not redirect us on(http://www.myimmopix.com/fr/multiple-uplaod/) page that displayed following message.
![image](https://cloud.githubusercontent.com/assets/14847553/13248961/674a4bc2-da47-11e5-8ae4-419e6ef23f2a.png)
![image](https://cloud.githubusercontent.com/assets/14847553/13248767/42ace762-da46-11e5-8b14-654a3cef910b.png)

**Comment by narendra-addweb** [comment]
Please set relative links for slider buttons as you like. You can set these buttons link from below path.

Admin > LayerSlider WP > Slider "Slider démarrage" > Slide #1/2/3 > Button layer

**Comment by Maxfavier** [comment]
1/ "Démarrer" should lead to the same place as the "Start" when logged out or "Upload Photos" when logged in.

2/ "En savoir plus" soude link to a part that is yet missing on the home page, where I present some advantages of the good real estate pictures.
The box should be designed as per the attachement with 2 columns. I also added the text for FR and ENG to this comment.
This extra box should be put between example and pricing box, with the same blue background as the "Tour" part.
![capture d ecran 2016-03-01 15 10 51](https://cloud.githubusercontent.com/assets/17143257/13429579/34622782-dfc1-11e5-81be-e7a3be6aedb4.png)
[Text en savoir plus.txt](https://github.com/narendra-addweb/MyImmoPix/files/152912/Text.en.savoir.plus.txt)

3/ The last "En savoir plus" should be replaced by "Nos services" and lead to the "Our services part".

If not clear, let me know.

**Comment by Maxfavier** [comment]
[Vastgoed fotografie.docx](https://github.com/narendra-addweb/MyImmoPix/files/179241/Vastgoed.fotografie.docx)
