### ISSUE TITLE
Header :

### ISSUE THREAD

**Issue by Krina-Addweb** [narendra-addweb/MyImmoPix#9]
Header links for SignUp & login is wrong right now.

**Comment by narendra-addweb** [comment]
Please check.

From now _Sign Up_  button will redirect on My account page for register and _Log In_ button remain same(Except remove _Register_ link).

**Comment by Maxfavier** [comment]
Ok, this seems fine. 
Only the rollover when selecting "Sign up" is wrong with red letters instead of white (see attachment)

<img width="340" alt="capture d ecran 2016-02-14 22 56 11" src="https://cloud.githubusercontent.com/assets/17143257/13036705/e9bb68fa-d36e-11e5-97c9-7ecd95821c37.png">
