### ISSUE TITLE
Checkout :

### ISSUE THREAD

**Issue by Krina-Addweb** [narendra-addweb/MyImmoPix#90]
![image](https://cloud.githubusercontent.com/assets/14847553/13249734/f4cf7554-da4b-11e5-982c-1339e09b5abc.png)

![image](https://cloud.githubusercontent.com/assets/14847553/13249684/ae69882a-da4b-11e5-9499-b1b312c515ab.png)

**Comment by Maxfavier** [comment]
I close the issue. That payment plateforme will be installed at a later stage (we need input from Raphaël on that part)
