### ISSUE TITLE
My account : Recent Orders

### ISSUE THREAD

**Issue by Krina-Addweb** [narendra-addweb/MyImmoPix#92]
When we click on Cancel link to cancel the recent order it should not gives us following errors.
![image](https://cloud.githubusercontent.com/assets/14847553/13253046/f53cdc70-da5f-11e5-8a79-dfc0ea4a69d2.png)

![image](https://cloud.githubusercontent.com/assets/14847553/13253034/dc626af8-da5f-11e5-8f22-fa11138b3372.png)

**Comment by narendra-addweb** [comment]
This issue is due to server settings, once we setup this on live server we will check for that.
