### ISSUE TITLE
Review project :

### ISSUE THREAD

**Issue by Krina-Addweb** [narendra-addweb/MyImmoPix#96]
When we upload images, Time duration for uploaded images are displaying wrong on project details page like when we upload images & click on next step, it display following time mentioned in screenshot & also for every time either we were uploading more photos for that project.
![image](https://cloud.githubusercontent.com/assets/14847553/13279151/87314b70-dafb-11e5-8553-72c7a31315ae.png)

**Comment by narendra-addweb** [comment]
We can keep it on the first upload base. 
See comments: [#103](https://github.com/narendra-addweb/MyImmoPix/issues/103)
