### ISSUE TITLE
Language specific : Error on project detail page

### ISSUE THREAD

**Issue by Krina-Addweb** [narendra-addweb/MyImmoPix#98]
Js error is displayed over project detail page![screen shot 2016-02-25 at 12 06 23 pm](https://cloud.githubusercontent.com/assets/14847553/13311890/3ebdd4a4-dbb8-11e5-9d69-3b36fe7718a3.png)

**Comment by vivek-addweb** [comment]
jQuery lib 'jquery.min.js' and 'jquery.js' both are called in this page. Pls remove 'jquery.min.js'
